Modified the in container hook to handle .c and .h files

diff --git a/git-hooks/pre-commit-in-container b/git-hooks/pre-commit-in-container
--- a/git-hooks/pre-commit-in-container
+++ b/git-hooks/pre-commit-in-container
@@ -22,6 +22,8 @@ trap "echo; echo git pre-commit hook failed." EXIT
 exec 1>&2
 
 changed_py_files=$( { git diff --cached --name-only | grep -E '\.py$'; } || true)
+changed_c_files=$( { git diff --cached --name-only | grep -E '\.c$'; } || true)
+changed_h_files+=$( { git diff --cached --name-only | grep -E '\.h$'; } || true)
 changed_go_files=$( { git diff --cached --name-only | grep -E '\.go$' | grep -v felixbackend.pb.go; } || true)
 
 copyright_owner="Tigera, Inc"
@@ -244,12 +246,108 @@ if $go_apache_check_failed; then
   echo "be added to the ${skip_file} file"
 fi
 
+BPF_GPL_DIR='./bpf-gpl'
+BPF_APACHE_DIR='./bpf-apache'
+
+c_gpl_license_check_failed=false
+c_apache_license_check_failed=false
+c_copyright_check_failed=false
+
+echo "Checking changed C files for copyright statements..."
+for filename in $changed_c_files; do
+  if [ ! -e  "${filename}" ]; then
+    continue
+  fi
+  if ! grep -q -E "$copyright_re" "${filename}"; then
+    echo "  Changed file is missing ${copyright_owner} copyright:" ${filename}
+    c_copyright_check_failed=true
+  fi
+done
+for filename in $changed_h_files; do
+  if [ ! -e  "${filename}" ]; then
+    continue
+  fi
+  if ! grep -q -E "$copyright_re" "${filename}"; then
+    echo "  Changed file is missing ${copyright_owner} copyright:" ${filename}
+    c_copyright_check_failed=true
+  fi
+done
+
+echo "Checking C files for GPL license statements..."
+files=$(find $BPF_GPL_DIR -name "*.c" -o -name "*.h")
+for file in $files; do
+  if ! grep -q -E "under the terms of the GNU General Public License" "${file}"; then
+    echo "  File is missing GPL license: bpf-gpl/"`basename $file`
+    c_gpl_license_check_failed=true
+  fi
+done
+
+echo "Checking C files for Apache license statements..."
+files=$(find $BPF_APACHE_DIR -name "*.c" -o -name "*.h")
+for file in $files; do
+  if ! grep -q -E "Licensed under the Apache License, Version 2.0" "${file}"; then
+    echo "  File is missing Apache license: bpf-apache/"`basename $file`
+    c_apache_license_check_failed=true
+  fi
+done
+
+if $c_copyright_check_failed; then
+  echo
+  echo "Copyright statement should match:"
+  echo
+  echo "  // ${copyright_re}"
+  echo "Example for new files:"
+  echo "  // Copyright (c) ${year} ${copyright_owner}. All rights reserved."
+  echo "Example for updated files (use commas and year ranges):"
+  echo "  // Copyright (c) 2012,2015-${year} ${copyright_owner}. All rights reserved."
+  echo 
+fi
+
+if $c_gpl_license_check_failed; then
+  echo
+  echo "GPL license header should be"
+  echo 
+  echo // This program is free software';' you can redistribute it and/or modify
+  echo // it under the terms of the GNU General Public License as published by
+  echo // the Free Software Foundation';' either version 2 of the License, or
+  echo // '('at your option')' any later version.
+  echo //
+  echo // This program is distributed in the hope that it will be useful,
+  echo // but WITHOUT ANY WARRANTY';' without even the implied warranty of
+  echo // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+  echo // GNU General Public License for more details.
+  echo //
+  echo // You should have received a copy of the GNU General Public License along
+  echo // with this program';' if not, write to the Free Software Foundation, Inc.,
+  echo // 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
+  echo 
+fi
+
+if $c_apache_license_check_failed; then
+  echo
+  echo "Apache license header should be:"
+  echo
+  echo '// Licensed under the Apache License, Version 2.0 (the "License");'
+  echo '// you may not use this file except in compliance with the License.'
+  echo '// You may obtain a copy of the License at'
+  echo '//'
+  echo '//     http://www.apache.org/licenses/LICENSE-2.0'
+  echo '//'
+  echo '// Unless required by applicable law or agreed to in writing, software'
+  echo '// distributed under the License is distributed on an "AS IS" BASIS,'
+  echo '// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.'
+  echo '// See the License for the specific language governing permissions and'
+  echo '// limitations under the License.'
+  echo 
+fi
+
 if $go_apache_check_failed || $go_copyright_check_failed || \
    $py_apache_check_failed || $py_copyright_check_failed || \
    $logrus_hook_check_failed || $focussing_check_failed || \
-   $junit_hook_check_failed || $stale_file_in_skip_files; then
+   $junit_hook_check_failed || $stale_file_in_skip_files || \
+   $c_copyright_check_failed || $c_gpl_license_check_failed || \
+   $c_apache_license_check_failed; then
   exit 1
 fi
-exec ./git-hooks/pre-commit-gpl-apache
 # Remove the trap handler.
 trap "" EXIT
