Markups.
- Update help text.
- Make sure CHERRY_PICK is set.

diff --git a/hack/cherry-pick-pull b/hack/cherry-pick-pull
--- a/hack/cherry-pick-pull
+++ b/hack/cherry-pick-pull
@@ -28,10 +28,41 @@ set -o pipefail
 
 function init-vars() {
   THIS_SCRIPT=$(basename "$0")
+
+  if [[ "$#" -lt 2 ]]; then
+    echo "${0} <remote branch> <pr-number>...: cherry pick one or more PRs onto <remote branch> and propose pull request"
+    echo
+    echo " Checks out <remote branch> and handles the cherry-pick of <pr> (possibly multiple) for you."
+    echo " Examples:"
+    echo "   ${THIS_SCRIPT} upstream/release-3.14 12345        # Cherry-picks PR 12345 onto upstream/release-3.14 and proposes that as a PR."
+    echo "   ${THIS_SCRIPT} upstream/release-3.14 12345 56789  # Cherry-picks PR 12345, then 56789 and proposes the combination as a single PR."
+    echo "   CHERRY_PICK=1 SRC_UPSTREAM_REMOTE=open-source DST_UPSTREAM_REMOTE=upstream ${THIS_SCRIPT} upstream/release-3.14 12345"
+    echo "   # ^- Uses git cherry-pick to pick PR 12345 as a single commit from the 'open-source' remote to the"
+    echo "   #    'upstream' remote's release-3.14 branch, and proposes that as a PR."
+    echo
+    echo " Environment variables:"
+    echo
+    echo "   Set SRC_UPSTREAM_REMOTE and DST_UPSTREAM_REMOTE (default for both: upstream) and FORK_REMOTE (default: origin)"
+    echo "   To override the default source and destination repos, and the repo to push the PR to."
+    echo
+    echo "   Set CHERRY_PICK=1 to use 'git cherry-pick' to pick the PR as a single commit (instead of the default, which"
+    echo "   uses 'git am' to preserve the PR's intermediate commits). Requires that the PR has already been merged."
+    echo
+    echo "   Set SQUASH_COMMITS=1 to apply the PR as a single commit using 'git apply'. This doesn't handle conflicts as"
+    echo "   well as 'git cherry-pick' (watch out for .rej files!), but it doesn't require the source PR to have been merged."
+    echo
+    echo "   Set DRY_RUN=1 to skip git push and creating PR. When DRY_RUN is set the script will leave you in a branch"
+    echo "   containing the commits you cherry-picked."
+    echo
+    echo "   Set REGENERATE_DOCS=1 to regenerate documentation for the target branch after picking the specified commits."
+    echo "   This is useful when picking commits containing changes to API documentation."
+    exit 2
+  fi
+
   REPO_ROOT="$(git rev-parse --show-toplevel)"
   declare -rg REPO_ROOT
   cd "${REPO_ROOT}"
-  
+
   STARTINGBRANCH=$(git symbolic-ref --short HEAD)
   declare -rg STARTINGBRANCH
   declare -rg REBASEMAGIC="${REPO_ROOT}/.git/rebase-apply"
@@ -52,6 +83,8 @@ function init-vars() {
     echo "Can't parse $DST_UPSTREAM_REMOTE URL to set DST_MAIN_REPO_ORG or DST_MAIN_REPO_NAME."
     exit 1
   fi
+  
+  CHERRY_PICK=${CHERRY_PICK:-""}
   SQUASH_COMMITS=${SQUASH_COMMITS:-""}
 
   if [[ -z ${GITHUB_USER:-} ]]; then
@@ -63,41 +96,12 @@ function init-vars() {
     echo "Can't find 'gh' tool in PATH, please install: https://cli.github.com/"
     exit 1
   fi
-  
-  if [[ "$#" -lt 2 ]]; then
-    echo "${0} <remote branch> <pr-number>...: cherry pick one or more PRs onto <remote branch> and propose pull request"
-    echo
-    echo "  Checks out <remote branch> and handles the cherry-pick of <pr> (possibly multiple) for you."
-    echo "  Examples:"
-    echo "    ${THIS_SCRIPT} upstream/release-3.14 12345        # Cherry-picks PR 12345 onto upstream/release-3.14 and proposes that as a PR."
-    echo "    ${THIS_SCRIPT} upstream/release-3.14 12345 56789  # Cherry-picks PR 12345, then 56789 and proposes the combination as a single PR."
-    echo "    SRC_UPSTREAM_REMOTE=open-source DST_UPSTREAM_REMOTE=upstream ${THIS_SCRIPT} upstream/release-3.14 12345"
-    echo "    # ^- Cherry-picks PR 12345 from the 'open-source' remote to the 'upstream' remote, to the upstream/release-3.14 base branch and proposes that as a PR."
-    echo
-    echo "  Set the DRY_RUN environment var to skip git push and creating PR."
-    echo "  This is useful for creating patches to a release branch without making a PR."
-    echo "  When DRY_RUN is set the script will leave you in a branch containing the commits you cherry-picked."
-    echo
-    echo "  Set the REGENERATE_DOCS environment var to regenerate documentation for the target branch after picking the specified commits."
-    echo "  This is useful when picking commits containing changes to API documentation."
-    echo
-    echo " Set SRC_UPSTREAM_REMOTE and DST_UPSTREAM_REMOTE (default for both: upstream) and FORK_REMOTE (default: origin)"
-    echo " To override the default remote names to what you have locally."
-    echo
-    echo " Use a different SRC_UPSTREAM_REMOTE and DST_UPSTREAM_REMOTE if you would like to cherry-pick a pull request"
-    echo " across different repos. For example, to cherry-pick a pull request from the repo defined as the 'open-source'"
-    echo " remote into the repo defined as 'upstream', use SRC_UPSTREAM_REMOTE=open-source DST_UPSTREAM_REMOTE=upstream."
-    echo
-    echo " Use SQUASH_COMMITS=1 if you want to have all original PR diffs consolidated into a single patch and applied with 'git apply',"
-    echo " otherwise all original commits in 'git format-patch' style will be applied with 'git am'"    
-    exit 2
-  fi
-  
+
   if git_status=$(git status --porcelain --untracked=no 2>/dev/null) && [[ -n "${git_status}" ]]; then
     echo "!!! Dirty tree. Clean up and try again."
     exit 1
   fi
-  
+
   if [[ -e "${REBASEMAGIC}" ]]; then
     echo "!!! 'git rebase' or 'git am' in progress. Clean up and try again."
     exit 1
@@ -109,16 +113,16 @@ function init-vars() {
 
   function join { local IFS="$1"; shift; echo "$*"; }
   declare -rg PULLDASH=$(join - "${PULLS[@]/#/#}") # Generates something like "#12345-#56789"
-  
+
   # Pre-compute markdown links for each PR.
   declare -ag PULLLINK
   for pull in "${PULLS[@]}"; do
     PULLLINK+=(  "${SRC_MAIN_REPO_ORG}/${SRC_MAIN_REPO_NAME}#${pull}" )
   done
-  
+
   echo "+++ Updating remotes..."
   git remote update "${SRC_UPSTREAM_REMOTE}" "${DST_UPSTREAM_REMOTE}" "${FORK_REMOTE}"
-  
+
   if ! git log -n1 --format=%H "${BRANCH}" >/dev/null 2>&1; then
     echo "!!! '${BRANCH}' not found. The second argument should be something like ${DST_UPSTREAM_REMOTE}/release-0.21."
     echo "    (In particular, it needs to be a valid, existing remote branch that I can 'git checkout'.)"
@@ -166,9 +170,9 @@ trap return_to_kansas EXIT
 function make-a-pr() {
   echo
   echo "+++ Creating a pull request on GitHub at ${GITHUB_USER}:${NEWBRANCH}"
-  
+
   local rel="$(basename "${BRANCH}")"
-  
+
   # Shorten release-calient-v3.xx to v3.xx.
   local relshort="${rel#release-}"
   relshort="${relshort#calient-}"
@@ -223,7 +227,7 @@ function make-a-pr() {
     else
       # If there's only one PR, strip off any previous cherry-pick title.
       # This gives a nice result when cherry-picking a previous pick.
-      pull_body=$(echo "${pull_body}" | head -n 1 | grep -v "## Cherry-pick history"; 
+      pull_body=$(echo "${pull_body}" | head -n 1 | grep -v "## Cherry-pick history";
                   echo "${pull_body}" | tail -n +2 )
     fi
     new_body+="${pull_body}"
@@ -240,7 +244,7 @@ function make-a-pr() {
   fi
 
   pr_body_file="$(mktemp -t prtext.XXXX)" # cleaned in return_to_kansas
-  
+
   cat >"${pr_body_file}" <<EOF
 ${new_header}${new_body}
 ${META_BLOCK:-}
@@ -250,7 +254,7 @@ EOF
     echo "!!! Skipping PR creation. PR text would have been:"
     echo
     cat "${pr_body_file}"
-  else 
+  else
     if gh repo set-default --view 2>&1 | grep -q "No default remote"; then
       echo "+++ Default repo must be set. Running: gh repo set-default"
       gh repo set-default
@@ -324,17 +328,22 @@ function create-branch-and-pr() {
           exit 1
         fi
       done
-  
+
       if [[ "${conflicts}" != "true" ]]; then
         echo "!!! git cherry-pick / am / git apply failed, likely because of an in-progress 'git am' or 'git rebase'"
         exit 1
       fi
     fi
-  
+
     # When squashing, commit patch changes with the same message as the merge commit from the original PR
     if [[ -n "${SQUASH_COMMITS}" ]]; then
       merge_commit_hash=$(gh pr view --repo "${SRC_MAIN_REPO_ORG}/${SRC_MAIN_REPO_NAME}" ${pull}  --json mergeCommit -q .mergeCommit.oid)
-      git commit -C ${merge_commit_hash}
+      if [[ -z "${merge_commit_hash}" || "${merge_commit_hash}" == "null" ]]; then
+        echo "!!! PR ${pull} has bad/missing merge commit (perhaps it's not merged yet?), using generic commit message."
+        git commit -m "Pick ${SRC_MAIN_REPO_ORG}/${SRC_MAIN_REPO_NAME}#${pull}"
+      else
+        git commit -C "${merge_commit_hash}"
+      fi
     fi
 
     # remove the patch file from /tmp
