AAA

diff --git a/felix/.semaphore/publish-artifacts b/felix/.semaphore/publish-artifacts
--- a/felix/.semaphore/publish-artifacts
+++ b/felix/.semaphore/publish-artifacts
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
-# Copyright (c) 2023 Tigera, Inc. All rights reserved.
+
+# Copyright (c) 2020 Tigera, Inc. All rights reserved.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -12,6 +13,18 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-#
 
-exec gcloud --quiet compute ssh "--zone=${ZONE}" "ubuntu@${VM_NAME}" -- -A -o ServerAliveInterval=10 "$@"
+# No set -e so that we continue to collect artifacts even if some fail.
+set -x
+
+# set nullglob so that '*' is not used literally if the artifacts dir is empty
+shopt -s nullglob
+
+my_dir=$(dirname "$0")
+repo_dir=$my_dir/..
+
+cd "$repo_dir/artifacts" || exit 1
+
+for file in *; do
+  artifact push --expire-in 4w job "$file"
+done
