Fix

diff --git a/.semaphore/collect-artifacts b/.semaphore/collect-artifacts
--- a/.semaphore/collect-artifacts
+++ b/.semaphore/collect-artifacts
@@ -31,38 +31,36 @@ done
 
 cd "$repo_dir" || exit 1
 
-mkdir -p "$artifacts_dir"
+mkdir -p "artifacts"
 
 if [ "$COMPONENT" = "felix" ]; then
 
   echo "Collecting artifacts for felix..."
-  felix_dir="$repo_dir/felix"
   for file in /tmp/core_felix* ; do
     if [ -f "$file" ]; then
       echo "Adding core file: $file"
       sudo chmod a+r "$file"
-      out_file="$artifacts_dir/$(basename "$file").xz"
+      out_file="artifacts/$(basename "$file").xz"
       xz < "$file" > "$out_file"
     fi
   done
-  races="$felix_dir/fv/data-races.log"
+  races="felix/fv/data-races.log"
   if [ -s "$races" ]; then
     # Only save the log if it's non-empty.
     xz < "$races" > artifacts/data-races.log.xz
   fi
   if ! $skip_binaries; then
     tar -cJf artifacts/binaries.tar.xz \
-      "$felix_dir/bin/calico-felix-amd64" \
-      "$felix_dir/bin/calico-bpf" \
-      "$felix_dir/bin/"test-*
+      "felix/bin/calico-felix-amd64" \
+      "felix/bin/calico-bpf" \
+      "felix/bin/"test-*
   fi
-  cp -r "$felix_dir/report" "$artifacts_dir/" || echo "Failed to copy felix reports."
+  cp -r "felix/report" "artifacts/" || echo "Failed to copy felix reports."
 
 elif [ "$COMPONENT" = "node" ]; then
 
   echo "Collecting artifacts for node..."
-  node_dir="$repo_dir/node"
-  cp -r "$node_dir/report" "$artifacts_dir/" || echo "Failed to copy node reports."
+  cp -r "node/report" "artifacts/" || echo "Failed to copy node reports."
 
 fi
 
diff --git a/.semaphore/vms/collect-artifacts-from-vms b/.semaphore/vms/collect-artifacts-from-vms
--- a/.semaphore/vms/collect-artifacts-from-vms
+++ b/.semaphore/vms/collect-artifacts-from-vms
@@ -43,7 +43,7 @@ for batch in "${batches[@]}"; do
     if [ "$batch" != 1 ]; then
       args+=("--skip-binaries")
     fi
-    VM_NAME=$vm_name "$my_dir/on-test-vm" "${CALICO_DIR_NAME}/.semaphore/collect-artifacts" "${args[@]}" || echo "Failed to collect artifacts from ${vm_name}."
+    VM_NAME=$vm_name "$my_dir/on-test-vm" COMPONENT=${COMPONENT} "${CALICO_DIR_NAME}/.semaphore/collect-artifacts" "${args[@]}" || echo "Failed to collect artifacts from ${vm_name}."
     timeout 10m gcloud --quiet compute scp "--zone=${ZONE}" "ubuntu@${vm_name}:${CALICO_DIR_NAME}/artifacts" "${repo_dir}/artifacts/${batch}" --recurse || echo "Failed to SCP from ${vm_name}"
   ) >& "$log_file" &
   pid=$!
