Knobble prereq.

diff --git a/.semaphore/collect-artifacts b/.semaphore/collect-artifacts
--- a/.semaphore/collect-artifacts
+++ b/.semaphore/collect-artifacts
@@ -34,6 +34,7 @@ cd "$repo_dir" || exit 1
 mkdir -p "$artifacts_dir"
 
 if [ "$COMPONENT" = "felix" ]; then
+
   echo "Collecting artifacts for felix..."
   felix_dir="$repo_dir/felix"
   for file in /tmp/core_felix* ; do
@@ -55,6 +56,14 @@ if [ "$COMPONENT" = "felix" ]; then
       "$felix_dir/bin/calico-bpf" \
       "$felix_dir/bin/"test-*
   fi
+  cp -r "$felix_dir/report" "$artifacts_dir/" || echo "Failed to copy felix reports."
+
+elif [ "$COMPONENT" = "node" ]; then
+
+  echo "Collecting artifacts for node..."
+  node_dir="$repo_dir/node"
+  cp -r "$node_dir/report" "$artifacts_dir/" || echo "Failed to copy node reports."
+
 fi
 
 exit 0
diff --git a/.semaphore/vms/collect-artifacts-from-vms b/.semaphore/vms/collect-artifacts-from-vms
--- a/.semaphore/vms/collect-artifacts-from-vms
+++ b/.semaphore/vms/collect-artifacts-from-vms
@@ -20,7 +20,7 @@ my_dir="$(dirname $0)"
 repo_dir="$my_dir/../.."
 
 # COMPONENT might be node or felix; give shellcheck something to work with.
-# shellcheck source=../felix/.semaphore/batches.sh
+# shellcheck source=../../felix/.semaphore/batches.sh
 source "${repo_dir}/${COMPONENT}/.semaphore/batches.sh"
 
 vm_name_prefix=$1
@@ -40,11 +40,11 @@ for batch in "${batches[@]}"; do
   (
     args=()
     # Only collect binaries once since they're large to copy and should be identical.
-    if [ $batch != 1 ]; then
+    if [ "$batch" != 1 ]; then
       args+=("--skip-binaries")
     fi
-    VM_NAME=$vm_name $my_dir/on-test-vm .semaphore/collect-artifacts "${args[@]}" || echo "Failed to collect artifacts from ${vm_name}."
-    timeout 10m gcloud --quiet compute scp "--zone=${ZONE}" "ubuntu@${vm_name}:${REPO_NAME}/artifacts" ./ --recurse || echo "Failed to SCP from ${vm_name}"
+    VM_NAME=$vm_name "$my_dir/on-test-vm" "${CALICO_DIR_NAME}/.semaphore/collect-artifacts" "${args[@]}" || echo "Failed to collect artifacts from ${vm_name}."
+    timeout 10m gcloud --quiet compute scp "--zone=${ZONE}" "ubuntu@${vm_name}:${CALICO_DIR_NAME}/artifacts" "${repo_dir}/artifacts/${batch}" --recurse || echo "Failed to SCP from ${vm_name}"
   ) >& "$log_file" &
   pid=$!
   pids+=( "$pid" )
