Fix artifact collection.

diff --git a/.semaphore/collect-artifacts b/.semaphore/collect-artifacts
--- a/.semaphore/collect-artifacts
+++ b/.semaphore/collect-artifacts
@@ -14,13 +14,13 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-set -e
+# No set -e so that we continue to collect artifacts even if some fail.
 set -x
 
 my_dir="$(dirname "$0")"
 repo_dir="$my_dir/.."
 
-cd "$repo_dir"
+cd "$repo_dir" || exit 1
 
 rm -rf artifacts
 mkdir -p artifacts
@@ -28,7 +28,8 @@ for file in /tmp/core_felix* ; do
   if [ -f "$file" ]; then
     echo "Adding core file: $file"
     sudo chmod a+r "$file"
-    xz < "$file" > "artifacts/$(basename "$file").xz"
+    out_file="artifacts/$(basename "$file").xz"
+    xz < "$file" > "$out_file"
   fi
 done
-tar -cJf artifacts/binaries.tar.xz bin/calico-felix bin/calico-bpf
+tar -cJf artifacts/binaries.tar.xz bin/calico-felix-amd64 bin/calico-bpf
